#pragma once
#define CLOCK_TICKS_PER_SECOND 4194304
//#define CLOCK_TICKS_PER_MICROSECOND CLOCK_TICKS_PER_SECOND/1000000
#define SECONDS_PER_TICK 1/CLOCK_TICKS_PER_SECOND
#define NANOSECONDS_PER_TICK 238
